version: "3"
services:
  shorturl:
    build:
      context: .
      dockerfile: Dockerfile
    image: shorturl:0.1.0
    container_name: shorturl
    restart: always
    volumes:
      - ./data:/data
    command: "-dbpath /data/urls.db -urllen 4"
    ports:
      - "18000:8000"
